on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

name: Continuous Deployment

jobs:
  build:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with: { release-type: node }

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

  publish-npm:
    runs-on: ubuntu-latest

    if: ${{ needs.release-please.outputs.release_created }}
    needs:
      - build
      - release-please

    environment:
      name: npm
      url: https://www.npmjs.com/package/@cprecioso/tsconfig

    permissions:
      contents: read
      id-token: write

    steps:
      - run: sudo npm install -g npm

      - uses: actions/download-artifact@v8
        with:
          name: package.tgz
          skip-decompress: true

      - run: npm publish --provenance --access public package.tgz
