on:
  workflow_dispatch:
  workflow_call:

name: Publish

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v3

      - uses: actions/setup-node@v6
        with: { cache: "yarn" }

      - run: yarn pack -o package.tgz

      - uses: actions/upload-artifact@v7
        with:
          path: package.tgz
          archive: false
          if-no-files-found: error

  publish-npm:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: npm
      url: https://www.npmjs.com/package/@cprecioso/tsconfig

    permissions:
      contents: read
      id-token: write

    steps:
      - run: npm install -g npm

      - uses: actions/download-artifact@v8
        with:
          name: package.tgz
          skip-decompress: true

      - run: npm publish --provenance --access public package.tgz
