on:
  push:
    branches:
      - main

name: Release

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: "@cprecioso/tsconfig"

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

  publish:
    needs: [release-please]
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    if: ${{ needs.release-please.outputs.release_created }}
